// React-Práctica/TiendaGuitarras/src/App.jsx
import Header from "./components/header.jsx";
import Guitarra from "./components/Guitarra.jsx";
import { useEffect, useState } from "react";
import { db } from "./data/db.js";

function App() {

    //Recuperamos los datos de localStorage para poder iniciar el state
    // como corresponda según si tiene articulos o no
    const carritoInicial = () => {
        const localStorageCarrito = localStorage.getItem('carrito')
        //Si hay un carrito guardado en localStorage, lo recuperas y lo conviertes a array(parse)
        //Si no hay carrito (es null), empieza con un array vacío.
        return (localStorageCarrito != null) ? JSON.parse(localStorageCarrito) : [];
    }

    const [data] = useState(db);
    const [carrito, setCarrito] = useState(carritoInicial)

   //Añadimos el articulo nuevo al carrito en localStorage
   //useEffect ejecuta la función cada vez que cambie algo dentro de su lista de dependencias
   //en este caso 'carrito'
    useEffect(() => {
        localStorage.setItem('carrito', JSON.stringify(carrito))
    }, [carrito])

    function anyadircarrito(articulo) {
        //Se busca dentro del array carrito el articulo clicado a través del id
        const articuloExiste = carrito.findIndex(element => articulo.id === element.id);

        if (articuloExiste >= 0) {
            //Copia del carrito (NO se puede modificar el ORIGINAL)
            const copiaCarrito = [...carrito];

            //Se agrega la cantidad al articulo existente en la COPIA
            copiaCarrito[articuloExiste].cantidad++;

            //Se modifica el estado del carrito con la copia modificada
            setCarrito(copiaCarrito);


        } else {
            //Se crea el atributo cantidad si la guitarra no existia
            //anteriormente
            articulo.cantidad = 1;
            setCarrito(carrito => [...carrito, articulo])
        }

    }

    function eliminarDelCarrito(id) {
        const nuevoCarrito = () => carrito.filter(element => element.id !== id);
        setCarrito(nuevoCarrito);
    }

    function disminuirCantidad(id) {
        const copiaCarrito = [...carrito];

        const articuloExiste = carrito.findIndex(element => element.id === id);

        if(copiaCarrito[articuloExiste].cantidad !== 1)
        //Se agrega la cantidad al articulo existente en la COPIA
        copiaCarrito[articuloExiste].cantidad--;

        //Se modifica el estado del carrito con la copia modificada
        setCarrito(copiaCarrito);
    }

    
    function aumentarCantidad(id) {

        const copiaCarrito = [...carrito];

        const articuloExiste = carrito.findIndex(element => element.id === id);

        //Se agrega la cantidad al articulo existente en la COPIA
        copiaCarrito[articuloExiste].cantidad++;

        //Se modifica el estado del carrito con la copia modificada
        setCarrito(copiaCarrito);

    }

    function vaciarCarrito(){
        setCarrito([])
    }

    return (
        <>

            <Header
                //Le pasamos el state carrito al header (para pintarlo dinamicamente)
                carrito={carrito}
                eliminarDelCarrito={eliminarDelCarrito}
                disminuirCantidad={disminuirCantidad}
                aumentarCantidad={aumentarCantidad}
                vaciarCarrito = {vaciarCarrito}
            />
            <main className="container-xl mt-5">
                <h2 className="text-center">Nuestra Colección</h2>

                <div className="row mt-5">
                    {data.map(element => (
                        <Guitarra
                            key={element.id}
                            guitarraObj={element}
                            anyadircarrito={anyadircarrito}
                        />
                    ))}

                </div>
            </main>

            <footer className="bg-dark mt-5 py-5">
                <div className="container-xl">
                    <p className="text-white text-center fs-4 mt-4 m-md-0">GuitarLA - Todos los derechos Reservados</p>
                </div>
            </footer>
        </>
    )
}

export default App

// Vue-Práctica/Vue-TiendaGuitarras/src/App.vue
<script setup>
import { ref, reactive, onMounted } from 'vue';
import { db } from './data/guitarras';
import { watch } from 'vue';
import Guitarra from './components/Guitarra.vue';
import Header from './components/Header.vue';
import Footer from './components/Footer.vue';


const guitarras = ref([])
const carrito = ref([])
const guitarra = ref({})


//Le da el valor al array cuando se monte
onMounted(() => {
    guitarras.value = db; //ref
    //El valor de la guitarra promocional será la guitarra en la posición 2 del array guitarras
    guitarra.value = guitarras.value[2]

    const localStorageCarrito = localStorage.getItem('carrito')
    if (localStorageCarrito !== null) {
        carrito.value = JSON.parse(localStorageCarrito)
    }
})

const guardarLocalStorage = () => {
    localStorage.setItem('carrito', JSON.stringify(carrito.value))
}

watch(carrito, () => {
    guardarLocalStorage()
}, {
    deep: true
}
)


const agregar_carrito = (guitarra) => {
    const articuloExiste = carrito.value.findIndex(articulos => articulos.id === guitarra.id);

    if (articuloExiste >= 0) {
        //Copia del carrito (NO se puede modificar el ORIGINAL)
        const copiaCarrito = [...carrito.value];

        //Se agrega la cantidad al articulo existente en la COPIA
        copiaCarrito[articuloExiste].cantidad++;

        carrito.value = copiaCarrito;

    } else {
        guitarra.cantidad = 1;
        carrito.value.push(guitarra);
    }

}

const decrementarCantidad = (guitarra) => {
    const articuloIndex = carrito.value.findIndex(articulos => articulos.id === guitarra.id);

    if (articuloIndex >= 0) {
        //Copia del carrito
        const copiaCarrito = [...carrito.value];

        if (copiaCarrito[articuloIndex].cantidad > 1) {
            // Si la cantidad es mayor a 1, solo decrementa

            copiaCarrito[articuloIndex].cantidad--;

            //La copia sustituye el carrito original
            carrito.value = copiaCarrito;
        }
    }
}

const incrementarCantidad = (guitarra) => {
    const articuloIndex = carrito.value.findIndex(articulos => articulos.id === guitarra.id);

    if (articuloIndex >= 0) {
        const copiaCarrito = [...carrito.value];
        //Incrementa la cantidad del articulo
        copiaCarrito[articuloIndex].cantidad++;
        carrito.value = copiaCarrito;
    }
}

const vaciarCarrito = () => {
    carrito.value = ([])
}

const eliminarProducto = (guitarra) => {
    const nuevoCarrito = () => carrito.value.filter(element => element.id !== guitarra.id);
    carrito.value = nuevoCarrito()
}

</script>

<template>
    <Header :carrito="carrito" @decrementarCantidad="decrementarCantidad" @incrementarCantidad="incrementarCantidad"
        :guitarra="guitarra" @agregar-carrito="agregar_carrito" @vaciarCarrito="vaciarCarrito"
        @eliminarProducto="eliminarProducto" />

    <main class="container-xl mt-5">
        <h2 class="text-center">Nuestra Colección</h2>

        <div class="row mt-5">
            <!--Aplicamos la directiva dentro del componente donde está el html para imprimir las guitarras
            Guitarra.vue; Esto :guitarra = "guitarra" pasa la informacion al componente-->
            <Guitarra v-for="guitarra in guitarras" :guitarra="guitarra" :key="guitarra.id"
                @agregar-carrito="agregar_carrito" />
        </div>
    </main>

    <Footer />



</template>

<style></style>
