// React/TiendaGuitarras/src/components/Header.jsx
import {useMemo} from 'react';

export default function Header({carrito, eliminarDelCarrito, disminuirCantidad, aumentarCantidad, vaciarCarrito }){
//Obtenemos el carrito
//Se pinta con MAP, no usar FOREACH

//State derivado
//useMemo se ejecuta si ha ocurrido algún cambio
//Si las dependencias no cambian, React devuelve el valor memorizado y no ejecuta la función otra vez.
const carritoVacio = useMemo(() => carrito.length === 0, [carrito]); //La dependencia está entre []

//State derivado total
//Suma los valores de la segunda variable dentro de la primera y los acumula
// ,0 es el valor inicial de 'total'
const carritoTotal = useMemo(() => carrito.reduce((total,element) => total + (element.cantidad * element.price),0), [carrito]);
    return(
        
          <header className="py-5 header">
        <div className="container-xl">
            <div className="row justify-content-center justify-content-md-between">
                <div className="col-8 col-md-3">
                    <a href="index.html">
                        <img className="img-fluid" src="./public/img/logo.svg" alt="imagen logo" />
                    </a>
                </div>
                <nav className="col-md-6 a mt-5 d-flex align-items-start justify-content-end">
                    <div 
                        className="carrito"
                    >
                        <img className="img-fluid" src="./public/img/carrito.png" alt="imagen carrito" />

                        <div id="carrito" className="bg-white p-3">
                            {carritoVacio ? (
                             <p className="text-center">El carrito esta vacio</p>

                            ) : (
                            <table className="w-100 table">
                                <thead>
                                    <tr>
                                        <th>Imagen</th>
                                        <th>Nombre</th>
                                        <th>Precio</th>
                                        <th>Cantidad</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {carrito.map(element => (

                                    <tr key={element.id}>
                                        <td>
                                            <img className="img-fluid" src={`/img/${element.image}.jpg`} alt="imagen guitarra" />
                                        </td>
                                        <td>{element.name}</td>
                                        <td className="fw-bold">
                                                {element.price}€
                                        </td>
                                        <td className="flex align-items-start gap-4">
                                            <button
                                                type="button"
                                                className="btn btn-dark"
                                                onClick={() => disminuirCantidad(element.id)}
                                            >
                                                -
                                            </button>
                                                {element.cantidad}
                                            <button
                                                type="button"
                                                className="btn btn-dark"
                                                 onClick={() => aumentarCantidad(element.id)}
                                            >
                                                +
                                            </button>
                                        </td>
                                        <td>
                                            <button
                                                className="btn btn-danger"
                                                type="button"
                                                onClick={() => eliminarDelCarrito(element.id)}
                                            >
                                                X
                                            </button>
                                        </td>
                                    </tr>
                                       ))}
                                </tbody>
                            </table>
                              )}
                            <p className="text-end">Total pagar: <span className="fw-bold">{carritoTotal}€</span></p>
                            <button className="btn btn-dark w-100 mt-3 p-2" onClick={() => vaciarCarrito()}>Vaciar Carrito</button>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </header>
        
    )


}

// Vue-Práctica/Vue-TiendaGuitarras/src/components/Header.vue
<script setup>
import { computed } from 'vue';


//Obtiene el prop guitarra enviado por app.vue
const props = defineProps({
    carrito: {
        type: Array,
        required: true
    },
    //Prop de guitarra promocional
    guitarra: {
        type: Object,
        required: true
    },

})

const totalPagar = computed(() => {
    return props.carrito.reduce((total, producto) =>
        total + (producto.cantidad * producto.precio),
        0);
})

const emit = defineEmits([
    'decrementarCantidad',
    'incrementarCantidad',
    'agregar-carrito',
    'vaciarCarrito',
    'eliminarProducto'

])
</script>


<template>
    <header class="py-5 header">
        <div class="container-xl">
            <div class="row justify-content-center justify-content-md-between">
                <div class="col-8 col-md-3">
                    <a href="index.html">
                        <img class="img-fluid" src="/img/logo.svg" alt="imagen logo">
                    </a>
                </div>
                <nav class="col-md-6 a mt-5 d-flex align-items-start justify-content-end">
                    <div class="carrito">
                        <img class="img-fluid" src="/img/carrito.png" alt="imagen carrito" />

                        <div id="carrito" class="bg-white p-3">
                            <p class="text-center m-0" v-if="carrito.length == 0">El carrito esta vacio</p>
                            <div v-else>
                                <table class="w-100 table">
                                    <thead>
                                        <tr>
                                            <th>Imagen</th>
                                            <th>Nombre</th>
                                            <th>Precio</th>
                                            <th>Cantidad</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr v-for="guitarra in carrito" :key="guitarra.id">
                                            <td>
                                                <img class="img-fluid" :src="`/img/${guitarra.imagen}.jpg`"
                                                    alt="imagen guitarra">
                                            </td>
                                            <td>{{ guitarra.nombre }}</td>
                                            <td class="fw-bold">
                                                {{ guitarra.precio }}€
                                            </td>
                                            <td class="flex align-items-start gap-4">
                                                <button type="button" class="btn btn-dark"
                                                    @click="$emit('decrementarCantidad', guitarra)">
                                                    -
                                                </button>
                                                {{ guitarra.cantidad }}
                                                <button type="button" class="btn btn-dark"
                                                    @click="$emit('incrementarCantidad', guitarra)">
                                                    +
                                                </button>
                                            </td>
                                            <td>
                                                <button class="btn btn-danger" type="button"  @click="$emit('eliminarProducto', guitarra)">
                                                    X
                                                </button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                                <p class="text-end">Total pagar: <span class="fw-bold">{{ totalPagar }}€</span></p>
                                <button class="btn btn-dark w-100 mt-3 p-2"  @click="$emit('vaciarCarrito')">Vaciar Carrito</button>
                            </div>
                        </div>
                    </div>
                </nav>
            </div><!--.row-->

            <div class="row mt-5">
                <div class="col-md-6 text-center text-md-start pt-5">
                    <h1 class="display-2 fw-bold">Modelo VAI</h1>
                    <p class="mt-5 fs-5 text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus,
                        possimus quibusdam dolor nemo velit quo, fuga omnis, iure molestias optio tempore sint at ipsa
                        dolorum odio exercitationem eos inventore odit.</p>
                    <p class="text-primary fs-1 fw-black">399€</p>
                    <button type="button" class="btn fs-4 bg-primary text-white py-2 px-5"
                        @click="$emit('agregar-carrito', guitarra)">Agregar al Carrito
                    </button>
                </div>
            </div>
        </div>

        <img class="header-guitarra" src="/img/header_guitarra.png" alt="imagen header">
    </header>
</template>
